import Head from 'next/head';
import {createClient} from 'next-sanity';
import PortableText from 'react-portable-text';

export default function Home({blogs}) {
  console.log(blogs)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1 className='text-rose-400 bg-gray-200 mx-8'>{blogs[0].title}</h1>
    <div className='mx-8'>
    <PortableText
      content={blogs[0].content}
      projectId =  'y4vol20y'
      dataset =  'production'
      serializers={{
        h1: (props) => <h1 style={{ color: "red" }} {...props} />,
        li: ({ children }) => <li className="special-list-item">{children}</li>
      }}
    />
    </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  const client =  createClient({
    projectId: 'y4vol20y', 
    dataset: 'production',
    useCdn: true 
  })
  
  const query = `*[_type == "blog"]`;
  const blogs = await client.fetch(query);
  return{
    props: {
      blogs
    }
  }
}
